version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=dataProject  
    volumes: 
      - pgdata:/data/postgres  
  app: 
    build: .
    container_name: project
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /app/node_modules  

volumes: 
  pgdata:
    driver: local